(* symbols *)
open_paren = "(";
close_paren = ")";
open_brace = "{";
close_brace = "}";
semicolon = ";";
equal = "=";
plus = "+";
minus = "-";
asterisk = "*";
slash = "/";
percent = "%";
bang = "!";
greater_than = ">";
less_than = "<";
ampersand = "&";
pipe = "|";
caret = "^";

symbols = open_paren | close_paren | open_brace | close_brace | semicolon
        | equal | plus | minus | asterisk | slash | percent | bang 
        | greater_than | less_than | ampersand | pipe | caret;

(* symbols with meaning*)
add = plus;
subtract = minus;
negate = minus;
multiply = asterisk;
divide = slash;
remainder = percent;
bit_not = bang;
shift_right = greater_than, greater_than;
shift_left = less_than, less_than;
bit_and = ampersand;
bit_or = pipe;
bit_xor = caret;

strong_arrow_right = equal, greater_than;

pre_op = negate | bit_not;
binary_op = add | subtract | multiply | divide | remainder 
          | shift_right | shift_left | bit_and | bit_or | bit_xor;

(* keywords *)
def = "def";
fun = "fun";
return = "return";

all_keywords = def | fun | return;

(* Numbers *)
zero = "0";
decimal_number = "0".."9";

decimal_literal = decimal_number, {decimal_number};

integer = decimal_literal;

(* identifiers *)
anonymous = "_";
valid = '_' | 'a'..'z' | 'A'..'Z' | decimal_number;
valid_first = valid - decimal_number;

identifier = (valid_first, {valid}) - (anonymous | all_keywords);

(* program *)

program = { top_level_statement };

top_level_statement = def_statement;
def_statement = def, function_definition;

statement = return_statement | expression_or_assignment_statement;
(* In the final grammar, return is an expression, not a statement *)
return_statement = return, expression, semicolon;
expression_or_assignment_statement = expression_or_assignment, semicolon;

(* In the final grammar, functions are much more complicated *)
function_definition = fun, identifier, open_paren, close_paren, (
  strong_arrow_right, expression, semicolon | 
  block
);

block = open_brace, {statement}, close_brace;

expression_or_assignment = expression;
expression = expression_atom 
           | pre_expression;

expression_atom = open_paren, expression, close_paren
                | integer;

pre_expression = pre_op, expression;