name: build
run-name: Build nn compiler
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: sergiovan/nn-github-actions
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
      - name: Set up repo
        run: CC=clang CXX=clang++ bash setup.sh
      - name: Compile nn
        run: cmake --build build/release $@
      - name: Publish nn compiler
        uses: actions/upload-artifact@v4
        with:
          name: NN Release compiler
          path: output/Release/nn
          if-no-files-found: error
  test:
    runs-on: ubuntu-latest
    container:
      image: sergiovan/nn-github-actions
    needs: build
    steps:
      # Step setup
      - name: Check out repo
        uses: actions/checkout@v4
      - name: Set up python venv
        run: python3 -m venv .venv && . .venv/bin/activate && echo PATH=$PATH >> $GITHUB_ENV
      - name: Upgrade pip
        run: python3 -m pip install --upgrade pip
      - name: Install python requirements
        run: pip install -r tests/requirements.txt
      # Artifact handling
      - name: Set up compiler location
        run: mkdir -p output/Release
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: NN Release compiler
          path: output/Release/
      - name: Make compiler executable...
        run: chmod +x output/Release/nn
      # Actual test run
      - name: Run tests
        run: python3 tests/run.py --compiler output/Release/nn
        continue-on-error: true
      - name: Publish run toml
        uses: actions/upload-artifact@v4
        with:
          name: Test result toml
          path: tests/past_runs.toml
          if-no-files-found: warn

  build-debug:
    runs-on: ubuntu-latest
    container:
      image: sergiovan/nn-github-actions
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
      - name: Set up repo
        run: CC=clang CXX=clang++ bash setup.sh
      - name: Compile nn
        run: cmake --build build/debug $@
      - name: Publish nn compiler
        uses: actions/upload-artifact@v4
        with:
          name: NN Debug compiler
          path: output/Debug/nn
          if-no-files-found: error
  test-debug:
    runs-on: ubuntu-latest
    container:
      image: sergiovan/nn-github-actions
    needs: build-debug
    steps:
      # Step setup
      - name: Check out repo
        uses: actions/checkout@v4
      - name: Set up python venv
        run: python3 -m venv .venv && . .venv/bin/activate && echo PATH=$PATH >> $GITHUB_ENV
      - name: Upgrade pip
        run: python3 -m pip install --upgrade pip
      - name: Install python requirements
        run: pip install -r tests/requirements.txt
      # Artifact handling
      - name: Set up compiler location
        run: mkdir -p output/Debug
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: NN Debug compiler
          path: output/Debug/
      - name: Make compiler executable...
        run: chmod +x output/Debug/nn
      # Actual test run
      - name: Run tests
        run: python3 tests/run.py --compiler output/Debug/nn
        continue-on-error: true
      - name: Publish run toml
        uses: actions/upload-artifact@v4
        with:
          name: Test result toml
          path: tests/past_runs.toml
          if-no-files-found: warn
